name = "my-app"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-04-28"

[build]
command = "pnpm install && pnpm run build"
[build.upload]
format = "service-worker"

kv_namespaces = [
  { binding = "NFT_EVENTS", id = "<ignored>", preview_id = "<ignored>" }
]
